### PR TITLE
adding a few additional RPC methods

### PR DESCRIPTION
**Pull request by aupiff**
I want to add many more methods to make this library support the entire JSON RPC API, but first I need to get a feel for all the features of the library and ask a few questions.

Is the `INLINE` pragma useful in `Api.hs`? Does it only buy users of the library some efficiency or is necessary for some other reason? I ran a few tests and the functions seemed to work without it.

### CODE REVIEW

**Comment by aupiff** [comment]
I asked about `INLINE` because it makes the code a little harder to read in exchange for minor performance improvements (reducing number of function calls by one). I was suggesting that maybe, for readability sake, it would be good to remove the pragma.

Also, I want to make input and output types more descriptive. For example, `eth_blockNumber :: Provider a => Web3 a Text` would ideally be `eth_blockNumber :: Provider a => Web3 a Integer`. However, it might be a good idea to keep these underlying functions unchanged and create higher level functions that follow Haskell naming conventions. I might make a module called `Eth` so that most users invoke `Eth.blockNumber :: Provider a => Web3 a Integer` which calls the lower-level function `Internal.eth_blockNumber :: Provider a => Web3 a Text`.

Let me know what you think about these two suggestions.

In this PR, I'm focusing on `net_`- and `eth_`-prefixed methods.

Methods added:

- [ ] eth_getLogs
- [ ] eth_getBlockByNumber
- [ ] eth_blockNumber
- [ ] eth_getBlockTransactionCountByNumber
- [ ] eth_gasPrice

Methods to add:

- [ ] net_version
- [ ] net_peerCount
- [ ] net_listening
- [ ] eth_protocolVersion
- [ ] eth_syncing
- [ ] eth_coinbase
- [ ] eth_mining
- [ ] eth_hashrate
- [ ] eth_blockNumber
- [ ] eth_getStorageAt
- [ ] eth_getTransactionCount
- [ ] eth_getBlockTransactionCountByHash
- [ ] eth_getUncleCountByBlockHash
- [ ] eth_getUncleCountByBlockNumber
- [ ] eth_getCode
- [ ] eth_sign
- [ ] eth_sendRawTransaction
- [ ] eth_estimateGas
- [ ] eth_getTransactionByHash
- [ ] eth_getTransactionByBlockHashAndIndex
- [ ] eth_getTransactionByBlockNumberAndIndex
- [ ] eth_getTransactionReceipt
- [ ] eth_getUncleByBlockHashAndIndex
- [ ] eth_getUncleByBlockNumberAndIndex
- [ ] eth_newPendingTransactionFilter
- [ ] eth_getFilterLogs
- [ ] eth_getWork
- [ ] eth_submitWork
- [ ] eth_submitHashrate

**Comment by akru** [comment]
1.  In my opinion for readability of code pragmas can be moved to end of file, you are probably right pragmas between function signature and implementation makes some difficulties.

2. You are absolutely right, but not for any returned values an Aeson library can decode, for example, transaction hash should be decoded from hexadecimal `Text`. As solution of this issue may be we can create wrapped types for all returned types.

So, about `(U)Int256` datatype, it can be obtained by newtype from `Integer` but size restrictions and bounds makes some performance overhead. In my opinion, typesafety preferable then performance. But if we introduce 256-bit integer, we should introduce 8, 16, 32, 64 and 128 integers, signed and unsigned. It can be described in separate module, like `Network.Ethereum.Web3.Integer`.

I'm agree with `Eth` module creation for direct node communication calls like `blockNumber`.

**Comment by aupiff** [comment]
Ok, I've moved `INLINE` pragmas to the end of the file. I'm adding a few more methods today which I need for an application I'm working on. I'll finish adding all the RPC methods by Tuesday.

I'll open up and issue for creating the `Eth` module and introducing new, more descriptive types, all of which I expect to be `newtype` wrappers.

**Comment by aupiff** [comment]
@akru Also, I'll have to change the `CallMode` type to support all default block parameter options:
```
The following options are possible for the defaultBlock parameter:

HEX String - an integer block number
String "earliest" for the earliest/genesis block
String "latest" - for the latest mined block
String "pending" - for the pending state/transactions
```

Another thing, I'm testing all the functions as I add them. I'll submit an issue for integration testing using a `geth` node later.

**Comment by aupiff** [comment]
It may be wise to rename the `CallMode` type `BlockParameter`. What do you think?

**Comment by aupiff** [comment]
Haven't investigated the cause yet, but Travis fails intermittently while building `web3`...

Any ideas?

```
Configuring web3-0.5.5.0...
cabal: Encountered missing dependencies:
aeson -any,
attoparsec -any,
base16-bytestring -any,
cryptonite -any,
http-client -any,
http-client-tls -any,
memory -any,
text -any,
vector -any
```

**Comment by akru** [comment]
@aupiff I do not mind renaming `CallMode` to `BlockParameter` because it more descriptive name.

So, stack builds is success, in my opinion the evil in dependecies bounds.

**Comment by aupiff** [comment]
@akru This branch is ready to merge. Two methods have yet to be implemented because they require new types to be created. I will put this off for a future PR.

- to implement: `eth_syncing`, `eth_getTransactionReceipt`

Another note on the types: There are many Json RPC methods which potentially return `null`, for example, `getBlockByHash` return type is described as `Object - A block object, or null when no block was found`. I think the return type of the API function should be `Maybe Block` instead of `Block`. If you agree, we can make these changes in the forthcoming "descriptive types PR".

I did basic testing on all the functions I added; you can see a bit of this [here](https://github.com/blockmason/friend-in-debt/blob/7831adeccc9250125488b98f08a4648062165549/fid-cli/src/FiD/Cli/Main.hs#L98-L128)

**Comment by aupiff** [comment]
@akru the non-stack builds take a really long time and fail intermittently, so I've marked them as `allowed-failures`. This should be fixed in an upcoming testing PR. For now, the non-stack builds aren't terribly useful.

**Comment by akru** [comment]
Great! I will soon test your PR with parity and accept if have no issues coming.

**Comment by aupiff** [comment]
Caught one mistake I made and reverted to your former style of INLINE-ing to stay consistent with the rest of the codebase.

**Comment by akru** [comment]
With parity works fine,
So, do you want to make some additional commits?

**Comment by aupiff** [comment]
Nope, I made all the commits I needed to. Go ahead and merge.

**Comment by aupiff** [comment]
I saw that you closed the Travis issue so I reverted the Travis file to only allow GHC HEAD to fail.

Now you can definitely merge to master. All done.

**Pull request merged**
