### PR TITLE
reorganizing modules

### LINKED ISSUE #14: Module re-organization
From the point of view of Haskell, many RPC functions have non-standard names. I propose that these non-standard functions, e.g. `eth_blockNumber`, be placed in an `Internal` module and be made available to users of the library via an `Eth` module thus: `Eth.blockNumber`.

### PR DESCRIPTION
**Pull request by aupiff**
fixes #14 

Perhaps the only questionable name in this module scheme is in `src/Network/Ethereum/Web3/Web3.hs`, `Network.Ethereum.Web3.Web3`. I think it's fine, but I'm happy to hear suggestions.

### CODE REVIEW

**Comment by aupiff** [comment]
@akru looks like the travis build failures are back. Stack worked fine. In my 2nd commit, all the tests pass but there were failures in the third though the only changes were of comments. I'm going to reopen my travis issue.

I think this branch is OK to merge.

**Comment by akru** [comment]
So, as I can see you cut prefixes from JSONRPC method names too, Its really work?
https://github.com/airalab/hs-web3/pull/23/files#diff-7e61041b72b99c0c63c6cd6c22e3acb8R23

**Comment by aupiff** [comment]
The code works, if that's what you mean. We'll also have to write new docs.

I wanted to get rid of the prefixes most of all because I wanted to have standard camelcase names. I also think the module organization of `web3.js`, which I copied, is good:

https://github.com/ethereum/web3.js/tree/develop/lib/web3/methods

This PR doesn't create a new `methods` dir, however to hold all the JSON RPC methods.

In the `eth.js` file, for example, there are the following methods defined w/o prefixes:

```


var methods = function () {
    var getBalance = new Method({
        name: 'getBalance',
        call: 'eth_getBalance',
        params: 2,
        inputFormatter: [formatters.inputAddressFormatter, formatters.inputDefaultBlockNumberFormatter],
        outputFormatter: formatters.outputBigNumberFormatter
    });

    var getStorageAt = new Method({
        name: 'getStorageAt',
        call: 'eth_getStorageAt',
        params: 3,
        inputFormatter: [null, utils.toHex, formatters.inputDefaultBlockNumberFormatter]
    });

    var getCode = new Method({
        name: 'getCode',
        call: 'eth_getCode',
        params: 2,
        inputFormatter: [formatters.inputAddressFormatter, formatters.inputDefaultBlockNumberFormatter]
    });
```

I think a module serves the same purpose as the prefixes and it lets us write standard function names in Haskell.

**Comment by akru** [comment]
Yes, all right, but as you can see in

```
protocolVersion :: Provider a => Web3 a Text
{-# INLINE protocolVersion #-}
protocolVersion = remote "protocolVersion"
```

JSON RPC have no method "protocolVersion" but have "eth_protocolVersion". First argument of `remote` is JSON RPC method name.

**Comment by aupiff** [comment]
Whoops. My mistake. Thank you.

**Comment by aupiff** [comment]
I was lazy about testing! I'll work on thorough automated regression tests soon so this won't happen again. Might be a good thing to work on while figuring out the travis issue.

**Comment by aupiff** [comment]
Converted one of my projects to use this version of the code, everything seems to work.

**Comment by akru** [comment]
Hi! You are ready to merge this?

**Comment by aupiff** [comment]
Yes, everything is tested. Please merge.

I'm going to put up some examples and tests [here](https://github.com/aupiff/hs-web3-playground) in a few hours.

**Pull request merged**
