### PR TITLE
refactor(#127): Alternative implementation for combineEncodedValues

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by srghma** [comment]
2022-03-16-08pm-15-59-screenshot

what it wants?

**Comment by akru** [comment]
Looks like AbiType instance or constraint isn’t defined

**Comment by srghma** [comment]
@akru no, the `AbiType` IS ALREADY one of constraints for `mkEncodedValueSimple` (actually will rename it to `mkEncodedValue`), but `isDynamic` still fails (as if the `AbiType` is not here)

BUT in the commit I have deployed the `isDynamic` is called NOT in the `mkEncodedValueSimple` function, but one level up, in the `class`, that's why tests pass (except of windows tests, which is not my fault probably)

maybe it's some problem in ghc compiler itself

**Comment by akru** [comment]
How can I reproduce that error? May be better to include it into tests.

**Pull request merged**
