### PR TITLE
use lookupEnv instead of getEnv for non-shell-like environments

### PR DESCRIPTION
**Pull request by iostat**
Just noticed we used a `getEnv` in `Setup.hs` which can fail in some environments when `$_` isn't set to the parent process binary. This uses a safer `lookupEnv`.

### CODE REVIEW

**Comment by iostat** [comment]
Yeah, the `stack` detection is flaky at best. It's an unfortunate side effect of how Cabal works in general, where you're effectively building a custom program that uses the Cabal library to compile/install your application. Technically speaking, even checking `$_` isn't particularly reliable but works for the most common use case. Perhaps we should merge this in now (in case anyone is building off master) and open another issue for win32 support?

**Comment by akru** [comment]
This is so little pr, may be it possible to fix win32 build issue here?

**Comment by blinky3713** [comment]
what's the status on this one? Even if we're not doing the windows fix here, can we still merge it?

**Comment by akru** [comment]
Ok, still merge.

**Pull request merged**
