### PR TITLE
Testing Foundation

### PR DESCRIPTION
**Pull request by iostat**
We at FOAM have been working on some improvements to the hs-web3 library, and in the process have developed several tests (#8). This PR includes a foundation for unit tests, as well as some acceptance tests based on the SimpleStorage contract. If this foundation is accepted, we have several more tests in the works built around it that we would be glad to PR! (We'd like to see if this test suite setup makes sense for the library, and would rather not complicate the PR too much)

The rationale for splitting up unit and acceptance tests has to do with the fact that we use Truffle to compile and deploy the contracts used in the `live` tests, and thus we've added some Cabal/Stack build hooks to simplify the modify->test cycle. This is necessary due to the fact that Truffle outputs ABIs as it deploys contracts to the blockchain which are then spliced in w/ Template Haskell on the `live` compile stage. We realize that some developers may not need to test against an actual Web3 provider if they're just hacking on library internals (such as those that would be tested by the `unit` suite, e.g., ABI encoding/decoding), and this allows them to not have to be running a blockchain as part of that process. Additionally, Travis does not yet have an easy way to run a Web3 provider to do the `live` tests against anyway.

We will also be publicly releasing our internal `cliquebait` container soon, which runs a Geth node that simulates a real network for testing purposes that can be used on Travis to test the `live` tests shortly, and are planning to wire it up for use with hs-web3's CI as well.

### CODE REVIEW

**Comment by iostat** [comment]
This is rather odd, it seems like the build caching in Travis is doing something weird:

We have:
```
Downloading the latest package list from hackage.haskell.org
Skipping download: local and remote files match.
```
immediately followed by
```
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
```

I have to say, I'm not 100% certain what's happening here. Is there a way to perhaps purge the Travis build cache for this PR?

**Comment by blinky3713** [comment]
@akru also worth noting, as soon as this is merged i have a branch which fixes all the encoding bugs as well as the indexed events bugs and is thoroughly tested with unit tests

**Comment by iostat** [comment]
I was just able to run these tests successfully on a personal fork with the same HEAD as being PR'd, so I think these failures are just a Travis caching issue: https://travis-ci.org/iostat/hs-web3-cleantravis

**Comment by akru** [comment]
Hi! Glad to see this great PR!
So, I have some issues, the first I see high truffle integration to build process, is it really needed? May be hs-web3-solidity can be used for ABI extraction? The second, scripts on source root doesn’t seems good, may be you cano move it to ‘scripts’ or ‘bin’ for example.

**Comment by iostat** [comment]
The Truffle dependency is mostly to ensure that you have a clean and consistent environment. It ensures that when the tests run the contracts will be available on the blockchain and also ensures that the ABI that's generated/compiled and subsequently used in the Template Haskell actually reflects what's on the blockchain. I've set up the build such that you'll only need it if you're trying to compile and run the `live` tests, so someone casually using the library won't need to have it available. It can be taken out of course, but then there'd be a lot of boilerplate to get a consistent test harness as well as manual work to keep in mind when adding new contracts. Right now you just throw the contract into `contracts/` and add one line to `migrations/2_deploy_contracts.js` whereas without it you'll have to be manually passing contract ABIS and addresses and making sure that your blockchain is up-to-date in between test runs.

As far as scripts in the source root go, yeah that's definitely a good point. Will move it shortly!

**Pull request merged**
